## YAML Template.
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shopschema?useSSL=false
        username: root
        password: password


#JPA Settings
    jpa.hibernate.ddl_auto: create