## YAML Template.
spring:
    datasource:
        url: jdbc:mysql://shopdb:3306/shop-resources
        username: user
        password: password

    jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect


#JPA Settings
    jpa.hibernate.ddl_auto: create